### ISSUE TITLE
Screen shots are here

### ISSUE THREAD

**Issue by Permafacture** [Permafacture/terminal_windows#6]
![02](https://cloud.githubusercontent.com/assets/6076141/8990843/7579e8fa-36ba-11e5-90cb-3bc521ed3783.jpg)
![03](https://cloud.githubusercontent.com/assets/6076141/8990848/79d44544-36ba-11e5-9ebe-5ccf777c2827.jpg)

**Comment by AtengChen** [comment]
Beautiful UI! Adding more UI elements would be better!
